format = """
[â–‘â–’â–“](#a3aed2)\
[ ğŸ‹ ](bg:#a3aed2 fg:#090c0c)\
[î‚´](bg:#769ff0 fg:#a3aed2)\
$directory\
[î‚´](fg:#769ff0 bg:#394260)\
$git_branch\
$git_status\
[î‚´](fg:#394260 bg:#212736)\
$nodejs\
$rust\
$golang\
$php\
$java\
$julia\
$ocaml\
$zig\
$lua\
$python\
$ruby\
$dart\
$c\
$cpp\
$bun\
$deno\
$elixir\
$elm\
$haskell\
$kotlin\
$swift\
$scala\
[î‚´](fg:#212736 bg:#1d2230)\
$time\
[î‚´ ](fg:#1d2230)\
\n$character"""

[directory]
style = "fg:#e3e5e5 bg:#769ff0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "â€¦/"

[character]
success_symbol = "[     ó±ª](#fce100)"
error_symbol = "[â¯](red)"

[aws]
symbol = "îŒ½  "
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[buf]
symbol = "ï’ "
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[bun]
symbol = "î¯ "
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[c]
symbol = "î˜ "
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[cpp]
symbol = "î˜ "
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[cmake]
symbol = "î” "
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[conda]
symbol = "ï„Œ "
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[crystal]
symbol = "î˜¯ "
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[dart]
symbol = "î˜ "
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[deno]
symbol = "îŸ€ "
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[docker_context]
symbol = "ïŒˆ "
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[elixir]
symbol = "î˜­ "
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[elm]
symbol = "î˜¬ "
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[fennel]
symbol = "îš¯ "
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[fossil_branch]
symbol = "ï˜ "
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[gcloud]
symbol = "îŒ½  "
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[git_branch]
symbol = "ï˜ "
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[git_commit]
tag_symbol = ' ï’ '
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[golang]
symbol = "î˜§ "
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[guix_shell]
symbol = "ïŒ¥ "
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[haskell]
symbol = "î· "
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[haxe]
symbol = "î™¦ "
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[hg_branch]
symbol = "ï˜ "
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[hostname]
ssh_symbol = "î¬ "
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[java]
symbol = "î‰– "
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[julia]
symbol = "î˜¤ "
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[kotlin]
symbol = "î˜´ "
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[lua]
symbol = "î˜  "
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[memory_usage]
symbol = "ó°› "
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[meson]
symbol = "ó°”· "
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[nim]
symbol = "ó°†¥ "
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[nix_shell]
symbol = "ïŒ“ "
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[nodejs]
symbol = "îœ˜ "
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[ocaml]
symbol = "î™º "
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[os.symbols]
Alpaquita = "îª¢ "
Alpine = "ïŒ€ "
AlmaLinux = "ïŒ "
Amazon = "ï‰° "
Android = "ï…» "
Arch = "ïŒƒ "
Artix = "ïŒŸ "
CachyOS = "ïŒƒ "
CentOS = "ïŒ„ "
Debian = "ïŒ† "
DragonFly = "îŠ "
Emscripten = "ïˆ… "
EndeavourOS = "ï†— "
Fedora = "ïŒŠ "
FreeBSD = "ïŒŒ "
Garuda = "ó°›“ "
Gentoo = "ïŒ "
HardenedBSD = "ó°Œ "
Illumos = "ó°ˆ¸ "
Kali = "ïŒ§ "
Linux = "ïŒš "
Mabox = "î¬© "
Macos = "ïŒ‚ "
Manjaro = "ïŒ’ "
Mariner = "ï‡ "
MidnightBSD = "ï†† "
Mint = "ïŒ "
NetBSD = "ï€¤ "
NixOS = "ïŒ“ "
Nobara = "ï€ "
OpenBSD = "ó°ˆº "
openSUSE = "ïŒ” "
OracleLinux = "ó°Œ· "
Pop = "ïŒª "
Raspbian = "ïŒ• "
Redhat = "ïŒ– "
RedHatEnterprise = "ïŒ– "
RockyLinux = "ïŒ« "
Redox = "ó°€˜ "
Solus = "ó° ³ "
SUSE = "ïŒ” "
Ubuntu = "ïŒ› "
Unknown = "ïˆ­ "
Void = "ïŒ® "
Windows = "ó°² "

[package]
symbol = "ó°— "
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[perl]
symbol = "î™¾ "
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[php]
symbol = "î˜ˆ "
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[pijul_channel]
symbol = "ï˜ "
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[pixi]
symbol = "ó°— "
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[python]
symbol = "îˆµ "
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[rlang]
symbol = "ó°Ÿ” "
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[ruby]
symbol = "î‘ "
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[rust]
symbol = "ó±˜— "
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[scala]
symbol = "îœ· "
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[swift]
symbol = "î• "
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[zig]
symbol = "îš© "
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[gradle]
symbol = "î™  "
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Form
style = "bg:#1d2230"
format = '[[ ïº $time ](fg:#a0a9cb bg:#1d2230)]($style)'

